version: '3'

services:
  db:
    build:
      context: ./
      dockerfile: Dockerfile-mysql
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./mysql_db:/var/lib/mysql
    command: ['--default-authentication-plugin=mysql_native_password', '--sql-mode=NO_ENGINE_SUBSTITUTION']
    ports:
      - "9306:3306"
  web:
    build:
      context: ./
      dockerfile: Dockerfile-php
    volumes:
      - ./html:/var/www/html
    container_name: labcollector_php_server
    depends_on:
      - db
    ports:
      - "8100:80"
    stdin_open: true
    tty: true
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: db
      PMA_USER: labcollector
      PMA_PASSWORD: labcollector
    ports:
      - "8101:80"
