FROM php:7.4-apache

COPY install_files/ioncube_loader_lin_7.4.so /labcollector/ioncube_loader_lin_7.4.so
COPY install_files/00-labcollector.ini /usr/local/etc/php/conf.d/00-labcollector.ini
RUN apt-get update
RUN docker-php-ext-install mysqli
RUN docker-php-ext-install pdo_mysql
RUN apt-get install -y zlib1g-dev
RUN apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev \
  && docker-php-ext-configure gd \
     --with-freetype \
     --with-jpeg \
  && docker-php-ext-install gd

RUN a2enmod rewrite
EXPOSE 80
